#!/bin/sh

. /etc/rc.conf

welcome_msg()
{
  local ext_ipv4="" asterisk=""

  if [ -n "$EXTIF" ]; then
    ext_ipv4="$(ip -o addr show dev "$EXTIF" 2>/dev/null | awk '$3 == "inet" { split($4, field, "/"); print field[1]; }' | tr '\n' ' ')"
  fi

  if [ -x /usr/sbin/asterisk ]; then
    asterisk="$(/usr/sbin/asterisk -V)"
  fi

  memtotal="$(awk '/^MemTotal:/ { print int(($2 + 512) / 1024) }' /proc/meminfo 2>/dev/null)"
  memfree="$(awk '/^MemFree:/ { print int(($2 + 512) / 1024) }' /proc/meminfo 2>/dev/null)"

  echo -e "\n\n\033[40m\033[1;32m  Welcome to AstLinux, Release: $(cat /etc/astlinux-release)${asterisk:+ - $asterisk}  \033[0m"
  echo "
  System information (as of $(date))

       Hostname: $HOSTNAME
         Domain: $DOMAIN
          Linux: $(uname -r)
     RAM Memory: $memtotal MB, Free $memfree MB

      Interface: $EXTIF (External)   IPv4 Address: $ext_ipv4${INTIF:+
      Interface: $INTIF (1st LAN)}${INT2IF:+
      Interface: $INT2IF (2nd LAN)}${INT3IF:+
      Interface: $INT3IF (3rd LAN)}${DMZIF:+
      Interface: $DMZIF (The DMZ)}
"
}

is_alert_sound_type()
{
  local sound_type="$1" sound IFS

  unset IFS
  for sound in $ALERT_SOUNDS; do
    if [ "$sound" = "$sound_type" ]; then
      return 0
    fi
  done

  return 1
}

start () {

  welcome_msg

  # Turn OFF the errorled (after finshed booting) 
  if grep -q "astlinux=net4801" /proc/cmdline; then

    echo 0 > /sys/class/leds/net48xx::error/brightness
  fi

  if grep -q "astlinux=wrap" /proc/cmdline; then

    echo 0 > /sys/class/leds/wrap::error/brightness
  fi

  if grep -q "astlinux=net5501" /proc/cmdline; then

    /usr/sbin/functions errorled_net5501 off
  fi

  if grep -q "astlinux=alix" /proc/cmdline; then

    echo 0 > /sys/class/leds/alix:2/brightness
  fi

  # LED control for Alix and WRAP boards (after finished booting)
  # "/mnt/kd/rc.ledcontrol" can override these settings
  if [ -x /mnt/kd/rc.ledcontrol ]; then
    /mnt/kd/rc.ledcontrol
  else
    if grep -q "astlinux=wrap" /proc/cmdline; then
    
      echo heartbeat > /sys/class/leds/wrap::power/trigger
      # echo ide-disk > /sys/class/leds/wrap::error/trigger
      if [ -n "$EXTIF" ]; then
        echo netdev > /sys/class/leds/wrap::extra/trigger
        echo "$EXTIF" > /sys/class/leds/wrap::extra/device_name 
        echo "enabled" > /sys/class/leds/wrap::extra/link
        echo "enabled" > /sys/class/leds/wrap::extra/transmit
        echo "enabled" > /sys/class/leds/wrap::extra/receive 
      fi   
    fi
    
    if grep -q "astlinux=alix" /proc/cmdline; then
    
      echo heartbeat > /sys/class/leds/alix:1/trigger
      # echo ide-disk > /sys/class/leds/alix:2/trigger
      if [ -n "$EXTIF" ]; then
        echo netdev > /sys/class/leds/alix:3/trigger
        echo "$EXTIF" > /sys/class/leds/alix:3/device_name 
        echo "enabled" > /sys/class/leds/alix:3/link
        echo "enabled" > /sys/class/leds/alix:3/transmit
        echo "enabled" > /sys/class/leds/alix:3/receive
   
      fi  
    fi
  fi

  # Generate Alert Sounds (after finished booting)
  if grep -q "astlinux=geni586" /proc/cmdline; then

    if is_alert_sound_type startup; then
      beep -f 330 -l 100 -d1 -n -f 277 -l 100 -d1 -n -f 330 -l 100 -d 1 -n -f 440 -l 330
    fi
  fi
}

stop () {

  # Turn on the errorled (on reboot/shutdown)
  if grep -q "astlinux=net4801" /proc/cmdline; then

    echo 1 > /sys/class/leds/net48xx::error/brightness
  fi

  if grep -q "astlinux=wrap" /proc/cmdline; then

    echo none > /sys/class/leds/wrap::power/trigger
    echo 1 > /sys/class/leds/wrap::power/brightness    
    # echo none > /sys/class/leds/wrap::error/trigger
    echo 1 > /sys/class/leds/wrap::error/brightness
    echo none > /sys/class/leds/wrap::extra/trigger
    echo 0 > /sys/class/leds/wrap::extra/brightness
  fi

  if grep -q "astlinux=net5501" /proc/cmdline; then
    
    /usr/sbin/functions errorled_net5501 on
  fi

  if grep -q "astlinux=alix" /proc/cmdline; then

    echo none > /sys/class/leds/alix:1/trigger
    echo 1 > /sys/class/leds/alix:1/brightness
    # echo none > /sys/class/leds/alix:2/trigger
    echo 1 > /sys/class/leds/alix:2/brightness
    echo none > /sys/class/leds/alix:3/trigger
    echo 0 > /sys/class/leds/alix:3/brightness
  fi

  # Generate Alert Sounds (on reboot/shutdown)
  if grep -q "astlinux=geni586" /proc/cmdline; then

    if is_alert_sound_type shutdown; then
      beep -f 988 -l 180 -d 33 -n -f 831 -l 110
    fi
  fi
}

case $1 in

  start)
    start
    ;;

  stop)
    stop
    ;;

  init)
    start
    ;;

  restart)
    stop
    sleep 2
    start
    ;;

  *)
    echo "Usage: start|stop|restart"
    ;;

esac
