#!/bin/sh

. /etc/rc.conf

start () {

  # Turn OFF the errorled (after finshed booting) 
  if grep -q "astlinux=net4801" /proc/cmdline; then

    echo 0 > /sys/class/leds/net48xx::error/brightness
  fi

  if grep -q "astlinux=wrap" /proc/cmdline; then

    echo 0 > /sys/class/leds/wrap::error/brightness
  fi

  if grep -q "astlinux=net5501" /proc/cmdline; then

    echo 0 > /dev/errorled
  fi

  if grep -q "astlinux=alix" /proc/cmdline; then

    echo 0 > /sys/class/leds/alix:2/brightness
  fi

  # LED control for Alix and WRAP boards (after finished booting)
  # "/mnt/kd/rc.ledcontrol" can override these settings
  if [ -x /mnt/kd/rc.ledcontrol ]; then
    /mnt/kd/rc.ledcontrol
  else
    if grep -q "astlinux=wrap" /proc/cmdline; then
    
      echo heartbeat > /sys/class/leds/wrap::power/trigger
      echo ide-disk > /sys/class/leds/wrap::error/trigger
      if [ -n "$EXTIF" ]; then
        echo netdev > /sys/class/leds/wrap::extra/trigger
        echo "$EXTIF" > /sys/class/leds/wrap::extra/device_name 
        echo "enabled" > /sys/class/leds/wrap::extra/link
        echo "enabled" > /sys/class/leds/wrap::extra/transmit
        echo "enabled" > /sys/class/leds/wrap::extra/receive 
      fi   
    fi
    
    if grep -q "astlinux=alix" /proc/cmdline; then
    
      echo heartbeat > /sys/class/leds/alix:1/trigger
      echo ide-disk > /sys/class/leds/alix:2/trigger
      if [ -n "$EXTIF" ]; then
        echo netdev > /sys/class/leds/alix:3/trigger
        echo "$EXTIF" > /sys/class/leds/alix:3/device_name 
        echo "enabled" > /sys/class/leds/alix:3/link
        echo "enabled" > /sys/class/leds/alix:3/transmit
        echo "enabled" > /sys/class/leds/alix:3/receive
   
      fi  
    fi
  fi

}

stop () {

  # Turn on the errorled (on reboot/shutdown)
  if grep -q "astlinux=net4801" /proc/cmdline; then

    echo 1 > /sys/class/leds/net48xx::error/brightness
  fi

  if grep -q "astlinux=wrap" /proc/cmdline; then

    echo none > /sys/class/leds/wrap::power/trigger
    echo 1 > /sys/class/leds/wrap::power/brightness    
    echo none > /sys/class/leds/wrap::error/trigger
    echo 1 > /sys/class/leds/wrap::error/brightness
    echo none > /sys/class/leds/wrap::extra/trigger
    echo 0 > /sys/class/leds/wrap::extra/brightness
  fi

  if grep -q "astlinux=net5501" /proc/cmdline; then
    
    echo 1 > /dev/errorled
  fi

  if grep -q "astlinux=alix" /proc/cmdline; then

    echo none > /sys/class/leds/alix:1/trigger
    echo 1 > /sys/class/leds/alix:1/brightness
    echo none > /sys/class/leds/alix:2/trigger
    echo 1 > /sys/class/leds/alix:2/brightness
    echo none > /sys/class/leds/alix:3/trigger
    echo 0 > /sys/class/leds/alix:3/brightness
  fi

}

case $1 in

  start|off)
    start
    ;;

  stop|on)
    stop
    ;;

  init)
    start
    ;;

  restart)
    stop
    sleep 2
    start
    ;;

  *)
    echo "Usage: start|stop|restart"
    ;;

esac
