#!/bin/sh

# Misc. startup stuff goes here...
# You probably shouldn't disable this one...

. /etc/rc.conf

init () {

  # Setup Hostname
  hostname "$HOSTNAME"

  if [ -n "$VI_EDITOR_OPTIONS" ]; then
    echo -e "$VI_EDITOR_OPTIONS" > /root/.exrc
  fi

  if [ -n "$ISSUE" ]; then
    echo "$ISSUE" > /tmp/etc/issue
  else
    echo "This is \n\ (\s \m \r) \t" > /tmp/etc/issue
  fi

  if [ -n "$NETISSUE" ]; then
    echo "$NETISSUE" > /tmp/etc/issue.net
  fi

  # local smartmontools drive database for smartctl
  if [ -f /mnt/kd/smart_drivedb.h ]; then
    ln -sf /mnt/kd/smart_drivedb.h /tmp/etc/smart_drivedb.h
  fi
}

start () {
  :
}

stop () {
  :
}

case $1 in

start)
  start
  ;;

stop)
  stop
  ;;

init)
  init
  start
  ;;

restart)
  stop
  sleep 2
  start
  ;;

*)
  echo "Usage: start|stop|restart"
  ;;

esac

