#!/bin/sh

. /etc/rc.conf

PIDFILE="/var/run/syslogd.pid"

start () {
  local LOGSIZE NLOGS

  if [ "$PERSISTLOG" = "yes" ]; then
    LOGSIZE=10240
    NLOGS=5
  else
    LOGSIZE=1024
    NLOGS=2
  fi

  echo "Starting syslogd..."
  syslogd -s $LOGSIZE -b $NLOGS
  klogd
}

stop () {
  if [ -f $PIDFILE ]; then
    echo "Stopping syslogd..."
    kill $(cat $PIDFILE) >/dev/null 2>&1
    rm -f $PIDFILE

    killall klogd >/dev/null 2>&1
  fi
}

case $1 in

start)
  start
  ;;

stop)
  stop
  ;;

init)
  start
  ;;

restart)
  stop
  sleep 2
  start
  ;;

*)
  echo "Usage start|stop|restart"
  ;;

esac
