#!/bin/sh

. /etc/rc.conf

if [ "$WDMODULE" = "auto" ]; then
  echo "Watchdog disabled, no 'auto' setting available for this target device."
  WDMODULE=""
fi

if [ -n "$WDTIME" ]; then
  TIMEOUT=$WDTIME
else
  TIMEOUT=30
fi

init () {

  if [ -n "$WDMODULE" ]; then
    modprobe $WDMODULE
  fi

}

start () {

  if [ -n "$WDMODULE" ]; then
    echo "Starting watchdog..."
    echo "Watchdog module: $WDMODULE"
    watchdog -t $TIMEOUT /dev/watchdog
  fi

}

stop () {

  if [ -n "$WDMODULE" ]; then
    if ps | grep -q -e '[ /]watchdog[ ]' -e '[ /]watchdog$'; then
      echo "Stopping watchdog...  (self-reboot within 60 seconds)"
      killall watchdog >/dev/null 2>&1
    fi
  fi

}

case $1 in

init)
  init
  start
  ;;

start)
  start
  ;;

stop)
  stop
  ;;

restart)
  stop
  sleep 2
  start
  ;;

*)
  echo "Usage: start|stop|restart"
  ;;

esac

