#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
#

APCUPSD_MSG="Power Failure !!!"

. /etc/apcupsd/astlinux.sh

exit 0
