#!/bin/sh

. /etc/rc.conf

if [ ! "$ASTBACK_PATHS" ]
then
echo "Please set the ASTBACK_PATHS variable in rc.conf"
exit 1
fi

if [ $1 ]
then
BACKFILE="$1"
else
BACKFILE="$ASTBACK_FILE"
fi

tar -czf $BACKFILE $ASTBACK_PATHS
