#!/bin/sh

if [ $1 ]
then
> /tmp/astdebug
DATE=`date`
echo "AstLinux Debug started at $DATE" >> /tmp/astdebug
echo "Sent by $1" >> /tmp/astdebug
echo >> /tmp/astdebug
echo >> /tmp/astdebug
echo "Interrupts" >> /tmp/astdebug
cat /proc/interrupts >> /tmp/astdebug
echo "CPUInfo" >> /tmp/astdebug
cat /proc/cpuinfo >> /tmp/astdebug
echo "Messages" >> /tmp/astdebug
dmesg >> /tmp/astdebug
echo "Processes" >> /tmp/astdebug
ps auwx >> /tmp/astdebug
echo "rc.conf" >> /tmp/astdebug
cat /etc/rc.conf >> /tmp/astdebug
echo "Interfaces" >> /tmp/astdebug
ifconfig -a >> /tmp/astdebug
echo "Routing Tables" >> /tmp/astdebug
netstat -rn >> /tmp/astdebug
echo "AstShape status" >> /tmp/astdebug
astshape status >> /tmp/astdebug
echo "Zaptel proc" >> /tmp/astdebug
cat /proc/zaptel/* >> /tmp/astdebug
echo "Kernel command line" >> /tmp/astdebug
cat /proc/cmdline >> /tmp/astdebug
echo "Kernel modules" >> /tmp/astdebug
lsmod
echo "AstLinux Version" >> /tmp/astdebug
cat /etc/astlinux-release >> /tmp/astdebug
echo "Zaptel config" >> /tmp/astdebug
cat /etc/zaptel.conf >> /tmp/astdebug
echo "uptime" >> /tmp/astdebug
uptime >> /tmp/astdebug
echo "Filesystems" >> /tmp/astdebug
mount >> /tmp/astdebug
echo >> /tmp/astdebug
df -h >> /tmp/astdebug
echo "Kernel Version" >> /tmp/astdebug
uname -a >> /tmp/astdebug
echo "Asterisk configs" >> /tmp/astdebug
for i in `ls /etc/asterisk`
do
echo "Asterisk $i" >> /tmp/astdebug
cat $i >> /tmp/astdebug
done

for j in `ls /etc/wanpipe/*.conf`
do
echo "Sangome $j" >> /tmp/astdebug
cat $j >> /tmp/astdebug
done

fi
