#!/bin/sh

if [ "$1" = "-h" ]; then
  echo "Usage:
$0 [number of beeps] [pause in microseconds]"
  exit
fi

if [ ! -r /dev/audio ]; then
  echo "Warning: No beep device node" 1>&2
  exit 1
fi

if [ -z "$1" ]; then
  BEEPS=1
else
  BEEPS="$1"
fi

if [ "$BEEPS" = "0" ]; then
  echo "Tricky tricky - 0 beeps is no beeps" 1>&2
  exit 1
fi

if [ "$BEEPS" != "1" -a -z "$2" ]; then
  echo "Error: If you have more than one beep I need a pause argument" 1>&2
  exit 1
fi

# Make noise
for i in `seq 1 $BEEPS`; do
  if ! echo -e "\a" >/dev/audio 2>/dev/null; then
    echo "Error: Beeping isn't supported on this machine" 1>&2
    exit 1
  fi

  if [ -n "$2" ]; then
    echo "Sleeping for $2 microseconds"
    usleep $2
  fi
done
