#!/bin/sh
##
## return the password filename and exit 0
## if the root/admin password needs changing
##

SYSTEM_ROOT_PASSWD="/etc/shadow"
HTPASSWD="$2"
WEB_GUI_HTPASSWD="${HTPASSWD:-/stat/var/www/admin/.htpasswd}"

case $1 in

root)
  if grep -q 'root:$1$$axJeFIpwicqOTwFpuoUAs1:' "$SYSTEM_ROOT_PASSWD" || [ ! -f "/mnt/asturw$SYSTEM_ROOT_PASSWD" ]; then
    echo "$SYSTEM_ROOT_PASSWD"
    exit 0
  fi
  ;;

admin)
  if [ -f "$WEB_GUI_HTPASSWD" ]; then
    if grep -q 'admin:6kERs0/UltqFI' "$WEB_GUI_HTPASSWD" || [ -z "$HTPASSWD" -a ! -f "/mnt/asturw$WEB_GUI_HTPASSWD" ]; then
      echo "$WEB_GUI_HTPASSWD"
      exit 0
    fi
  fi
  ;;

*)
  echo "Usage: check-default-passwd root|admin [path_to_.htpasswd]" >&2
  ;;

esac

exit 1

