#!/bin/sh
#
# AstLinux Shared Functions
#
# Execute via selector, do not include
#

gen_kd_files()
{
  # Args: dest_directory

  cp /stat/etc/rc.conf ${1}/
  cp -a /tmp/etc/asterisk ${1}/
  cp -a /var/spool/asterisk/voicemail ${1}/
  cp -a /tmp/tftpboot ${1}/

  mkdir ${1}/ssh
  cp -a /tmp/etc/ssh/ssh_host_* ${1}/ssh/

  mkdir ${1}/home
  mkdir ${1}/monitor
  mkdir ${1}/dictate

  mkdir ${1}/dahdi
  if [ -f /stat/etc/dahdi/system.conf ]; then
    cp -a /stat/etc/dahdi/system.conf ${1}/dahdi/
  else
    touch ${1}/dahdi/system.conf
  fi

  touch ${1}/webgui-prefs.txt

  if [ -f /var/db/dnsmasq.leases ]; then
    cp -a /var/db/dnsmasq.leases ${1}/
  else
    touch ${1}/dnsmasq.leases
  fi

  cp /stat/etc/dnsmasq.static ${1}/

  cp -a /var/log/asterisk/cdr-csv ${1}/

  if [ -d /stat/etc/wanpipe ]; then
    cp -a /stat/etc/wanpipe ${1}/
  fi

  cp -a /var/spool/cron/crontabs ${1}/

  if [ -f /var/db/astdb ]; then
    cp -a /var/db/astdb ${1}/
  else
    touch ${1}/astdb
  fi

  if [ -f /var/db/astdb.sqlite3 ]; then
    cp -a /var/db/astdb.sqlite3 ${1}/
  fi

  if [ -d /stat/etc/arno-iptables-firewall ]; then
    cp -a /stat/etc/arno-iptables-firewall ${1}/
  fi
}

# main

case $1 in

gen_kd_files)
  if [ -z "$2" ]; then
    echo "Usage: /usr/sbin/functions gen_kd_files target_directory"
    exit 1
  fi
  gen_kd_files "$2"
  ;;

*)
  echo "Usage: /usr/sbin/functions function_selector [args]"
  exit 1
  ;;

esac

