#!/bin/sh
# Not one of my cleanest creations, but it works. Look forward to some improvements in the future...

AUTO=YES

#Auto detect keydisk
for i in `cat /proc/cmdline`
do
if `echo $i | grep -q "astkd="`
then
KDDEV=`echo $i | grep "astkd=" | sed -e 's/astkd=//'`
AUTO=YES
else
KDDEV=/dev/sda1
AUTO=YES
fi
done

#Override auto detect on command line
if [ $1 ]
then
KDDEV="$1"
if `echo $1 | grep -q [1-8]`
then
AUTO=NO
KDDEV="$1"
else
KDDEV="$1"1
AUTO=YES
fi
fi

PARTDEV=`echo $KDDEV | tr -d 12345678`

if `mount | grep -q $KDDEV`
then
echo "A filesystem on $KDDEV is mounted.  Aborting."
exit
fi

echo "This script will help to create a KeyDrive to store
your AstLinux configuration.  MAKE SURE THAT YOUR DRIVE IS
CONNECTED.

I will use $KDDEV"

if [ "$AUTO" = "NO" ]
then
echo "USING EXISTING PARTITION.  MAKE SURE THIS IS WHAT YOU
WANT!!!"
fi

echo "Please type yes to continue"
echo
read -p"Is this okay? " RESPONSE

if [ ! "$RESPONSE" = "yes" ]
then
exit
fi

if [ "$AUTO" = "NO" ]
then
echo "You specified an existing partition.  I will attempt to
use it.  Skipping auto-partition..."
else
echo "Creating partition..."
if `echo ";" | sfdisk $PARTDEV > /dev/null 2> /dev/null`
then
echo "Partition created. Now making filesystem..."
else
echo "Partitioning failed. You are on your own."
fi
fi

if `mke2fs -q -L ASTKD $KDDEV`
then
echo "Filesystem created. Copying existing configuration..."
else
echo "Creating filesystem failed. You are on your own."
exit
fi

mount -t ext2 $KDDEV /mnt/kd

/usr/sbin/functions gen_kd_files /mnt/kd

echo "Done.  I STRONGLY URGE YOU TO REBOOT NOW."
echo "Type reboot to cleanly restart now."
