#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage:

$0 [filesystem]
" 1>&2
  exit 1
fi

DEV=$1

case $DEV in
  *[1-8]) PART=no ;;
  *) PART=yes ;;
esac

echo "This script will automatically create a read/write
filesystem to store your AstLinux configuration."

if [ "$PART" = "yes" ]; then
  echo "
WARNING: You have specified a disk, not a partition
we will automatically partition this disk for you, destroying
any existing partition table. This can be VERY dangerous
"
fi

echo "THIS SCRIPT WILL DESTROY EVERYTHING ON $DEV

ARE YOU SURE YOU WANT TO CONTINUE?

Please type yes to continue"

read -p "Are you sure? : " RETURN

if [ "$RETURN" != "yes" ]; then
  echo "$RETURN is not yes
Execution cancelled" 1>&2
  exit 1
fi

if mount | grep -q $DEV; then
  echo "$DEV is currently in use - aborting" 1>&2
  exit 1
fi

if findfs LABEL=ASTURW >/dev/null; then
  echo "
WARNING:
You already have a filesystem with the label ASTURW
This could confuse AstLinux when it boots.
I hope you know what you are doing...
Press enter to continue
"
  read
fi

if [ "$PART" = "yes" ]; then
  if echo ";" | sfdisk $DEV >/dev/null; then
DEV="${DEV}1"
    echo "Partition table created"
  else
    echo "Partitioning failed. You are on your own." 1>&2
  fi
fi

echo "Creating filesystem..."

mke2fs -q -L ASTURW $DEV

echo "Filesystem Created.

On new systems you can optionally use unionfs instead of they key disk.

To create the appropriate file structure, type yes.

If you have an existing key disk and want to migrate your key disk
settings to this new unionfs partition, execute movekd $DEV after
this script exits.

To create a new key disk structure on your new unionfs partition,
type yes followed by the Enter key.  Press any other key to exit.

If you are new to Astlinux, you will want to say yes."

read -p "Are you sure? : " RETURN

if [ "$RETURN" != "yes" ]; then
  echo "$RETURN is not yes"
  echo "Files not copied.  You may need to manually move or create
files.

You must reboot now or use movekd to migrate an existing key disk to
your new unionfs partition.
"
  exit 1
fi

echo "Copying files to $DEV"

mkdir /tmp/asturw
mount $DEV /tmp/asturw
mkdir -p /tmp/asturw/mnt/kd

/usr/sbin/functions gen_kd_files /tmp/asturw/mnt/kd

echo "Please reboot now or run movekd to migrate an existing key disk to your unionfs partition"

