#!/bin/sh

echo "This script will help to move a Key Disk to a unionfs
partition.  Please create your unionfs partition using genunion
before running this script."

ASTURW=`findfs LABEL=ASTURW`
KDDEV=`findfs LABEL=ASTKD`

if `mount | grep -q /mnt/kd`
  then
  echo "A filesystem on $KDDEV is mounted.  Good!  We'll assume you want
  move these files to unionfs."
else
  echo "No existing key disk mounted, we'll try to mount it"
  if `mount -t ext2 $KDDEV /mnt/kd`
    then
    echo "Key Disk Mounted."
  else
    echo "Unable to mount key disk.  Are you sure you have one?"
    exit
  fi
fi

if `mount |grep -q $ASTURW`
  then
  echo "Your unionfs partition is mounted"
else
  mkdir /tmp/asturw
  mount $ASTURW /tmp/asturw
fi

if [ -d /oldroot/mnt/asturw ]
  then
  mkdir -p /oldroot/mnt/asturw/mnt/kd
  cp -af /mnt/kd/* /oldroot/mnt/asturw/mnt/kd
  echo "Files copied"
else
  if [ -d /tmp/asturw ]
  then
  mkdir -p /tmp/asturw/mnt/kd
  cp -af /mnt/kd/* /tmp/asturw/mnt/kd
  echo "Files copied"
  fi
fi

e2label $KDDEV OLDKD

echo "Your key disk label has been changed to OLDKD.
If you wish to reverse this change, execute e2label $KDDEV ASTKD."

echo "All files copied.  I STRONGLY URGE YOU TO REBOOT NOW."
