#!/bin/sh
##
## Mass Deployment of IP Phones
##
## phoneprov-tools
##
## Copyright (C) 2014-2021 Lonnie Abelbeck and Michael Keuter
##
## This is free software, licensed under the GNU General Public License
## version 3 as published by the Free Software Foundation; you can
## redistribute it and/or modify it under the terms of the GNU
## General Public License; and comes with ABSOLUTELY NO WARRANTY.

usage()
{
  echo '
Usage: phoneprov-massdeployment [options...] in_file

Options:
  -a, --auto-pass         Automatically generate missing password(s)
  -A, --only-pass         Same as "-a, --auto-pass" without further processing
  -f, --force-overwrite   Overwrite existing files
  -h, --help              Show this help text
  -i, --if-name           Interface Name: INTIF, INT2IF, INT3IF, INT4IF, EXTIF, ethN, brN
                                          Defaults to config variable PHONEPROV_GW_IF
  -p, --partial           Partial input, append "dialplan" and "sip" entries to existing
  -r, --auto-reload       Automatically reload Asterisk "dialplan" and "sip" on success
  -R, --only-reload       Same as "-r, --auto-reload" without further processing
'
  exit 1
}

reload_asterisk()
{
  echo "Auto-reloading Asterisk 'dialplan' and 'sip'."

  if [ -x /mnt/kd/phoneprov-reload.script ]; then
    /mnt/kd/phoneprov-reload.script
  else
    asterisk -rx "dialplan reload" >/dev/null
    asterisk -rx "sip reload" >/dev/null
  fi
}

error_info() {
  local result="$1"

  if [ $result -eq 2 ]; then
    echo "phoneprov-massdeployment: Use -f or --force-overwrite option to overwrite."
    echo "Files left unchanged."
  elif [ $result -eq 3 ]; then
    echo "phoneprov-massdeployment: Use -a or --auto-pass option to automatically"
    echo "                          generate any missing password(s)."
  fi
}

extract_file() {
  local file="$1"

  cat "$file" | sed -e 's/^#.*//' -e 's/\t/ /g' -e 's/ *$//' -e '/^$/d'
}

gen_pass() {
  local data="$1" template mac_addr ext_cid ext pass

  template="$(echo "$data" | awk -F' ' '{ print $1; }')"
  mac_addr="$(echo "$data" | awk -F' ' '{ print $2; }')"
  ext_cid="$(echo "$data" | awk -F' ' '{ print $3; }')"
  pass="$(echo "$data" | awk -F' ' '{ print $4; }')"

  ext="$(echo "$ext_cid" | cut -d';' -f1 | cut -d'/' -f1)"

  if [ -n "$template" -a -n "$mac_addr" -a -n "$ext" ]; then
    if [ "$ext" != "init" -a "$ext" != "init-dialplan" -a "$ext" != "init-sip" ]; then
      if [ -z "$pass" ]; then
        pass="$(openssl rand -base64 12)"

        # Properly match if '*' exists in the extension/cid
        ext_cid="$(echo "$ext_cid" | sed 's/*/\\*/g')"

        sed -i -e "s|^${template}[ \t]*${mac_addr}[ \t]*${ext_cid}.*$|${template} ${mac_addr} ${ext_cid} ${pass}|" "$in_file"
      fi
    fi
  fi
}

sql_apply() {
  local ASTERISK_ODBC_SQLITE3 phoneprov_build

  ASTERISK_ODBC_SQLITE3="/mnt/kd/asterisk-odbc.sqlite3"

  phoneprov_build=$(sqlite3 -batch "$ASTERISK_ODBC_SQLITE3" <<EOF
SELECT count(*) FROM sqlite_master WHERE type='table' AND name='phoneprov_build';
EOF
  )
  if [ "$phoneprov_build" = "1" ]; then
    sqlite3 -batch "$ASTERISK_ODBC_SQLITE3" <<EOF
DROP TABLE IF EXISTS 'phoneprov';
ALTER TABLE 'phoneprov_build' RENAME TO 'phoneprov';
EOF
  else
    sqlite3 -batch "$ASTERISK_ODBC_SQLITE3" <<EOF
DROP TABLE IF EXISTS 'phoneprov';
EOF
  fi
}

ARGS="$(getopt --name phoneprov-massdeployment \
               --long auto-pass,only-pass,force-overwrite,help,if-name:,partial,auto-reload,only-reload \
               --options aAfhi:prR \
               -- "$@")"
if [ $? -ne 0 ]; then
  usage
fi
eval set -- $ARGS

auto_pass=0
only_pass=0
force_overwrite=0
partial=0
auto_reload=0
only_reload=0
if_name=""
while [ $# -gt 0 ]; do
  case "$1" in
    -a|--auto-pass)        auto_pass=1 ;;
    -A|--only-pass)        auto_pass=1 ; only_pass=1 ;;
    -f|--force-overwrite)  force_overwrite=1 ;;
    -h|--help)             usage ;;
    -i|--if-name)          if_name="$2"; shift ;;
    -p|--partial)          partial=1 ;;
    -r|--auto-reload)      auto_reload=1 ;;
    -R|--only-reload)      auto_reload=1 ; only_reload=1 ;;
    --) shift; break ;;
  esac
  shift
done
in_file="$1"

if [ $auto_reload -eq 1 -a $only_reload -eq 1 ]; then
  reload_asterisk
  exit 0
fi

if [ -z "$in_file" -o "$in_file" = "--" ]; then
  usage
fi
if [ ! -f "$in_file" ]; then
  echo "phoneprov-massdeployment: file not found: $in_file" >&2
  exit 1
fi

if [ $auto_pass -eq 1 ]; then
  echo "Auto-generating password(s):"

  temp_file="$(mktemp "${in_file}.XXXXXX")"
  cp "$in_file" "$temp_file"

  IFS=$'\n'
  extract_file "$temp_file" | while read data; do
    unset IFS
    gen_pass "$data"
  done
  unset IFS

  if cmp -s "$temp_file" "$in_file"; then
    echo "No missing password(s), input file left unchanged."
  else
    echo "Missing password(s) were added to input file."
  fi
  rm "$temp_file"

  if [ $only_pass -eq 1 ]; then
    exit 0
  fi
fi

options=""
if [ $force_overwrite -eq 1 ]; then
  options="$options${options:+ }-f"
fi
if [ -n "$if_name" ]; then
  options="$options${options:+ }-i $if_name"
fi

echo "Generating Phone Provisioning files:"

if [ $partial -eq 0 ]; then
  template_list=" "
  IFS=$'\n'
  extract_file "$in_file" | while read data; do
    unset IFS
    template="$(echo "$data" | awk -F' ' '{ print $1; }')"
    if ! echo "$template_list" | grep -q " $template "; then
      phoneprov-build $options $template 00:00:00:00:00:00 init
      result=$?
      if [ $result -ne 0 ]; then
        error_info $result
        exit $result
      fi
      template_list="$template_list$template "
    fi
  done
  result=$?
  unset IFS
  if [ $result -ne 0 ]; then
    exit $result
  fi
fi

IFS=$'\n'
extract_file "$in_file" | while read data; do
  unset IFS
  phoneprov-build $options $data
  result=$?
  if [ $result -ne 0 ]; then
    error_info $result
    exit $result
  fi
  printf "."
done
result=$?
unset IFS

if [ $result -ne 0 ]; then
  exit $result
fi

sql_apply

echo "Done"

if [ $auto_reload -eq 1 ]; then
  reload_asterisk
fi

exit 0

