#!/usr/bin/env bash

. /etc/rc.conf

ACME_REPO="/stat/etc/acme"

ACME_PROG="$ACME_REPO/acme.sh"

ACME_WORKING_DIR="/mnt/kd/acme"

export LE_WORKING_DIR="$ACME_WORKING_DIR"

LOCKFILE="/var/lock/acme-client.lock"

if [ ! -x "$ACME_PROG" ]; then
  echo "acme-client: executable file \"$ACME_PROG\" not found." >&2
  exit 1
fi

if [ ! -d "$ACME_WORKING_DIR" ]; then
  mkdir "$ACME_WORKING_DIR"
fi

if ! cd "$ACME_WORKING_DIR"; then
  exit 1
fi

# Robust 'bash' method of creating/testing for a lockfile
if ! ( set -o noclobber; echo "$$" > "$LOCKFILE" ) 2>/dev/null; then
  echo "acme-client: already running, lockfile \"$LOCKFILE\" exists, process id: $(cat "$LOCKFILE")." >&2
  exit 9
fi

gen_account_conf()
{
  if [ -f "$ACME_WORKING_DIR/account.static" ]; then
    echo "# Autogenerated.  Edit $ACME_WORKING_DIR/account.static file.
"
    cat "$ACME_WORKING_DIR/account.static"
    return
  fi

  echo "# Autogenerated.  Do not edit.
# A manually generated acme.sh config will use $ACME_WORKING_DIR/account.static if it exists.
"
  echo "USER_AGENT=\"AstLinux\""
}

trap 'rm -f "$LOCKFILE"; exit $?' INT TERM EXIT

gen_account_conf > "$ACME_WORKING_DIR/account.conf"

$ACME_PROG "$@"
rtn=$?

rm -f "$LOCKFILE"
trap - INT TERM EXIT

exit $rtn
