#!/bin/sh
##
## reload-blocklist-netset
##
## Regularly update .netset IP/Net entries to be used by Arno's Iptables Firewall (AIF)
##
## Cron may be used to run this script once or twice every day.  Example:
## 15 05,15 * * * reload-blocklist-netset /mnt/kd/blocklists firehol_level1 firehol_webclient >/dev/null 2>&1
##
## Important: Do not use the cron time schedule as above, make changes so the servers are not hit at the same time.
##
## Multiple netset entries may be space or comma separated.
##
## In this example, a /mnt/kd/blocklists/firehol_level1.netset
##              and a /mnt/kd/blocklists/firehol_webclient.netset file will be created.
## Note: The specified directory must pre-exist, it will not be created.
##
## This script prevents any netset from being updated more often than
## the defined 'AGE' value.
##

. /etc/rc.conf

DIR="$1"

UPDATES=0

FIREHOL="${BLOCKLIST_FIREHOL_ROOT_URL:-https://iplists.firehol.org/files}"

SPAMHAUS="${BLOCKLIST_SPAMHAUS_ROOT_URL:-https://www.spamhaus.org/drop}"

CUSTOM="${BLOCKLIST_CUSTOM_URLS}"

CUSTOMV6="${BLOCKLIST_CUSTOMV6_URLS}"

list_netsets()
{
  cat <<EOF

Available IPv4 Blocklist Netsets:
 firehol_level1: Blacklist composed from IP lists, providing maximum protection with minimum false positives.
 firehol_level2: Blacklist that track attacks, during about the last 48 hours.
 firehol_level3: Blacklist that track attacks, spyware, viruses, reported or detected in the last 30 days.
 firehol_webclient: Blacklist made from blocklists that a web client should never talk to. Use with firehol_level1.
         apiban: REST API for sharing IP addresses sending unwanted SIP traffic. Requires API Key via https://apiban.org/
       asterisk: Aggregate multiple Asterisk/SIP/VoIP blacklists, including blocklist_de_sip.
         voipbl: VoIP Blacklist - no longer maintained, not recommended.
  spamhaus_drop: Spamhaus DROP (Don't Route Or Peer), consisting of netblocks that are "hijacked" by cyber-crime operations.
 spamhaus_edrop: Spamhaus EDROP is an extension of the DROP list that includes suballocated netblocks.
         custom: Use variable BLOCKLIST_CUSTOM_URLS containing one or more (space/newline separated) URLs.

Available IPv6 Blocklist Netsets:
spamhaus_dropv6: Spamhaus DROPv6 list includes IPv6 ranges allocated to spammers or cyber criminals.
       customv6: Use variable BLOCKLIST_CUSTOMV6_URLS containing one or more (space/newline separated) URLs.

EOF
}

netset_url()
{
  local netset="$1"

  ## Defaults
  URL=""
  ALT_URL=""
  AGE=0
  FILTER=0
  ##

  case $netset in
  ## IPv4
    firehol_level1)
      URL="$FIREHOL/firehol_level1.netset"
      AGE=3600
      ;;
    firehol_level2)
      URL="$FIREHOL/firehol_level2.netset"
      AGE=3600
      ;;
    firehol_level3)
      URL="$FIREHOL/firehol_level3.netset"
      AGE=3600
      ;;
    firehol_webclient)
      URL="$FIREHOL/firehol_webclient.netset"
      AGE=3600
      ;;
     voipbl)
      URL="$FIREHOL/voipbl.netset"
      AGE=43200
      ;;
    spamhaus_drop)
      URL="$SPAMHAUS/drop.txt"
      ALT_URL="$FIREHOL/spamhaus_drop.netset"
      AGE=43200
      ;;
    spamhaus_edrop)
      URL="$SPAMHAUS/edrop.txt"
      ALT_URL="$FIREHOL/spamhaus_edrop.netset"
      AGE=43200
      ;;
    apiban)
      URL="apiban://"
      AGE=600
      ;;
    asterisk)
      URL="$FIREHOL/blocklist_de_sip.ipset"
      AGE=3600
      FILTER=0
      ;;
    custom)
      URL="$CUSTOM"
      AGE=3600
      FILTER=1
      ;;

  ## IPv6
    spamhaus_dropv6)
      URL="$SPAMHAUS/dropv6.txt"
      AGE=43200
      ;;
    customv6)
      URL="$CUSTOMV6"
      AGE=3600
      FILTER=2
      ;;
  esac
}

download_file()
{
  local file="$1" url="$2" mesg rtn

  if [ "${url%%:*}" = "apiban" ]; then
    if [ ! -f /mnt/kd/apiban.conf ]; then
      mesg="Missing API Key file: /mnt/kd/apiban.conf via https://apiban.org/"
      logger -s -t reload-blocklist-netset -p kern.info "$mesg"
      return 1
    fi
    apiban-netset > "$file"
    rtn=$?
    if [ $rtn -ne 0 ]; then
      mesg="apiban-netset: Error code: $rtn"
      logger -s -t reload-blocklist-netset -p kern.info "$mesg"
    fi
    return $rtn
  fi

  curl -sSfL --globoff --retry 1 --connect-timeout 15 --max-time 1800 -o "$file" "$url" >/dev/null
}

valid_update_age()
{
  local netset="$1" age="$2" file

  file="$DIR/$netset.netset"

  if [ -f "$file" ]; then
    if [ $(( $(date +%s) - $(date -r "$file" +%s) )) -lt $age ]; then
      return 1
    fi
  fi
  return 0
}

blocklist_netset()
{
  local netset url tmp_dir tmp_file tmp_index count mesg IFS

  IFS=' ,'
  for netset in $*; do
    unset IFS
    netset_url $netset
    if [ -z "$URL" ]; then
      echo "reload-blocklist-netset: Unknown Netset: $netset" >&2
      continue
    fi
    if ! valid_update_age $netset $AGE; then
      echo "reload-blocklist-netset: The file '$netset.netset' has been updated within $AGE seconds, skipping." >&2
      continue
    fi

    tmp_index=0
    tmp_dir="$(mktemp -d "/tmp/reload_blocklist_XXXXXX")"
    ## sanity check for tmp_dir since we are recursively removing later.
    if [ "${tmp_dir##/tmp/reload_blocklist_*}" != "" ] || [ ! -d "$tmp_dir" ]; then
      mesg="Creating temp directory for '$netset' netset failed, skipping."
      logger -s -t reload-blocklist-netset -p kern.info "$mesg"
      continue
    fi

    for url in $URL; do
      tmp_index=$((tmp_index + 1))
      tmp_file="$tmp_dir/netset$tmp_index.txt"

      if ! download_file "$tmp_file" "$url"; then
        if [ -z "$ALT_URL" ] || ! download_file "$tmp_file" "$ALT_URL"; then
          rm -rf "$tmp_dir"
          mesg="Retrieving '$netset' netset failed for '$url', skipping."
          logger -s -t reload-blocklist-netset -p kern.info "$mesg"
          break
        fi
      fi
      if grep -q -i -e '^<!DOCTYPE HTML' -e '^<HTML' "$tmp_file"; then
        rm -rf "$tmp_dir"
        mesg="Netset '$netset' text format is invalid for '$url', skipping."
        logger -s -t reload-blocklist-netset -p kern.info "$mesg"
        break
      fi
    done
    if [ -d "$tmp_dir" ]; then
      if [ $FILTER -eq 1 ]; then
        tmp_file="$tmp_dir/out.netset"
        iprange "$tmp_dir"/netset*.txt > "$tmp_file"
        if [ $? -ne 0 ]; then
          mesg="Aggregating '$netset' netset(s) failed, concatenating instead."
          logger -s -t reload-blocklist-netset -p kern.info "$mesg"
          cat "$tmp_dir"/netset*.txt > "$tmp_file"
        fi
      elif [ $FILTER -eq 2 ]; then
        tmp_file="$tmp_dir/out.netset"
        cat "$tmp_dir"/netset*.txt > "$tmp_file"
      fi
      cp "$tmp_file" "$DIR/$netset.netset"
      rm -rf "$tmp_dir"
      UPDATES=$((UPDATES + 1))

      count=$(grep -c '^[0-9a-fA-F]' "$DIR/$netset.netset")
      mesg="Netset '$netset' has been updated. Contains $count addresses/nets."
      logger -t reload-blocklist-netset -p kern.info "$mesg"
      echo "$mesg"
    fi
  done
}

if [ -z "$DIR" ]; then
  echo "Usage: reload-blocklist-netset netset_dir netset_1 [ netset_2 ... ]"
  list_netsets
  exit 1
fi

if [ ! -d "$DIR" ]; then
  echo "reload-blocklist-netset: Directory not found: $DIR"
  exit 1
fi

shift 1

if [ -z "$1" ]; then
  list_netsets
  exit 1
fi

blocklist_netset "$@"

if [ $UPDATES -gt 0 ]; then
  arno-iptables-firewall force-reload
fi

