#!/bin/sh

. /etc/rc.conf

PIDFILE="/var/run/acpid.pid"

init () {
  :
}

start () {

  if [ -x /usr/sbin/acpid -a -e /proc/acpi/event ]; then
    echo "Starting acpid..."

    /usr/sbin/acpid -p $PIDFILE
  fi
}

stop () {

  if [ -f $PIDFILE ]; then
    echo "Stopping acpid..."

    kill $(cat $PIDFILE) >/dev/null 2>&1
  fi
}

case $1 in

start)
  start
  ;;

stop)
  stop
  ;;

init)
  init
  start
  ;;

restart)
  stop
  sleep 2
  start
  ;;

*)
  echo "Usage: start|stop|restart"
  ;;

esac

