#!/bin/bash
#
# Use BuildRoot "post-build" script to overly board specific files
#

make_release_version()
{
  ASTURL="$(LANG=C svn info | awk -F': ' '/^URL:/ { print $2 }')"
  ASTBASE="$(basename ${ASTURL})"
  ASTREV="$(LANG=C svn info | awk -F': ' '/^Last Changed Rev:/ { print $2 }')"
  ASTEXTRA=""

  if [ "$(cat "project/astlinux/target_skeleton/etc/astlinux-release")" = "svn" ]; then
    ASTVER="astlinux-${ASTBASE}-${ASTREV}${ASTEXTRA}"
  else
    ASTVER="$(cat "project/astlinux/target_skeleton/etc/astlinux-release")${ASTEXTRA}"
  fi
}

overlay_target()
{
  local target_skeleton="$base/project/astlinux/board/$board/target_skeleton"

  if [ ! -d "$target_skeleton" ]; then
    exit_error "Source Directory not found: $target_skeleton"
  fi

  echo "
##
## Post Build Target Overlay: Board = \"$board\"
##
"

  cp -pv "$target_skeleton/etc/inittab" "$target/etc/inittab"

  cp -pv "$target_skeleton/etc/rc.modules" "$target/etc/rc.modules"

  if [ -f "$target_skeleton/stat/etc/sensors.conf" ]; then
    cp -pv "$target_skeleton/stat/etc/sensors.conf" "$target/stat/etc/sensors.conf"
  else
    rm -f "$target/stat/etc/sensors.conf"
  fi

  echo "
##
## Finished Target Overlay
##
"
}

exit_error()
{
  echo "
## ** ERROR **
## Post Build: Board = \"$board\"
## $1
"
  exit 1
}

target="$1"

base="${target%/output/target}"

if [ ! -f "$base/astlinux.board" ]; then
  echo "geni586" > "$base/astlinux.board"
fi

board="$(cat "$base/astlinux.board")"

if [ -z "$board" ] || [ ! -d "$base/project/astlinux/board/$board" ]; then
  exit_error "Unknown Board type."
fi

overlay_target

make_release_version
echo ${ASTVER} > "$target/etc/astlinux-release"

exit 0

