#!/bin/bash
#
# build-initrd [ force ]
#

save_state()
{
  cp -p .config .config.initrd.save
  cp -p initrd.config .config

  if [ -d "output" ]; then
    mv output output.initrd.save
  fi
}

restore_state()
{
  # This may be called multiple times on a interrupt
  # Only restore once
  if [ -f ".config.initrd.save" ]; then

    rm -rf output

    if [ -d "output.initrd.save" ]; then
      mv output.initrd.save output
    fi

    cp -p .config.initrd.save .config
    rm -f .config.initrd.save
  fi
}

umask 002

PATH=/sbin:/usr/sbin:$PATH

if [ -f "initrd.img" -a "$1" != "force" ]; then
  echo "The initrd image (initrd.img) already exists, skipping build."
  exit 0
fi

if [ ! -f "initrd.config" ]; then
  echo "The initrd.config file does not exist, exiting."
  exit 1
fi

save_state

trap 'restore_state; exit $?' INT TERM EXIT

make oldconfig

time make all

trap - INT TERM EXIT

if [ -f "output/images/rootfs.ext2.gz" ]; then
  echo "Installing initrd.img..."
  cp "output/images/rootfs.ext2.gz" "initrd.img"
else
  echo "Initrd build failed."
fi

restore_state

make oldconfig

exit 0

