#!/bin/bash
#
# master-upload input_path
#

input_path="$1"

auth_file="$HOME/.s3cfg"

success_count=0

upload_file()
{
  local remote_dir="$1" files="$2" count="$3" IFS=' ' file

  for file in $files; do
    s3cmd put --acl-public "$file" "s3://astlinuxmirror/$remote_dir/${file##*/}"
  done

  if [ $? -eq 0 ]; then
    if [ "$count" = "count" ]; then
      success_count=$((success_count+1))
    fi
  else
    echo "master-upload: failed."
    exit 1
  fi
}

upload_run_images()
{
  local local_dir="$1" firmware_path="$2" ver="/tmp/ver"

  for board in $(ls -1 "$local_dir"); do
    echo "Run Image for Board: $board"
    file="$(ls -1 "$local_dir/$board/"*.tar.gz | head -n1)"
    file_sha1="$(ls -1 "$local_dir/$board/"*.tar.gz.sha1 | head -n1)"
    if [ -n "$file" -a -n "$file_sha1" ]; then
      upload_file "$firmware_path/$board" "$file $file_sha1" count
    else
      echo "master-upload: missing file(s) in \"$local_dir/$board/\""
      exit 1
    fi

    # Successful upload, update the 'ver' file
    file_ver="$(basename "$file" .tar.gz)"
    echo "$file_ver" > "$ver"
    upload_file "$firmware_path/$board" "$ver"
    rm -f "$ver"
    echo ""
  done
}

upload_flash_images()
{
  local local_dir="$1" firmware_path="$2"

  for board in $(ls -1 "$local_dir"); do
    echo "Flash Image for Board: $board"
    file="$(ls -1 "$local_dir/$board/"*.img.gz | head -n1)"
    if [ -n "$file" ]; then
      upload_file "$firmware_path/$board" "$file" count
    else
      echo "master-upload: missing file(s) in \"$local_dir/$board/\""
      exit 1
    fi
    echo ""
  done
}

set_asterisk_version()
{
  case $1 in
    ast14)
      FIRMWARE="firmware-1.x"
      IMG="img"
      MIRROR_FIRMWARE="$FIRMWARE"
      MIRROR_IMG="downloads/img"
      ;;
    ast18)
      FIRMWARE="ast18-firmware-1.x"
      IMG="ast18-img"
      MIRROR_FIRMWARE="$FIRMWARE"
      MIRROR_IMG="downloads/img"
      ;;
    ast11)
      FIRMWARE="ast11-firmware-1.x"
      IMG="ast11-img"
      MIRROR_FIRMWARE="$FIRMWARE"
      MIRROR_IMG="downloads/img"
      ;;
    *)
      echo "master-upload: Unknown Asterisk Version."
      exit 1
      ;;
  esac
}

if [ -z "$input_path" ]; then
  echo "Usage: master-upload input_path"
  exit 1
fi

if [ ! -d "$input_path" ]; then
  echo "master-upload: directory \"$input_path\" not found."
  exit 1
else
  check_img=0
  check_firmware=0
  for dir in $(ls -1 "$input_path"); do
    case $dir in
      *img) check_img=1 ;;
      *firmware-1.x) check_firmware=1 ;;
    esac
  done
  if [ $check_img -eq 0 -o $check_firmware -eq 0 ]; then
    echo "master-upload: missing img/firmware-1.x directories."
    exit 1
  fi
fi

if [ ! -f "$auth_file" ]; then
  echo "master-upload: authentication file \"$auth_file\" not found."
  exit 1
fi

#
# Uplaod Asterisk 1.4, 1.8 and 11 versions of AstLinux
#

for asterisk in ast14 ast18 ast11; do

  set_asterisk_version $asterisk

  # Upload .tar.gz run images
  upload_run_images "$input_path/$FIRMWARE" "$MIRROR_FIRMWARE"

  # Upload .img.gz flash images
  upload_flash_images "$input_path/$IMG" "$MIRROR_IMG"

done

echo "
##
## Master Upload Finished for '$success_count' Images
##
"

