#!/bin/bash

TVER="1.1"

BRANCH="1.0"

if [ "${1:0:4}" != "${TVER}." ]; then
  echo "Usage: master-tag ${TVER}.x"
  exit 1
fi

RELEASE="astlinux-${1}"

ASTLINUX_RELEASE="project/astlinux/target_skeleton/etc/astlinux-release"

mark_release()
{
  echo "$RELEASE" > "$ASTLINUX_RELEASE"
}

mark_svn()
{
  echo "svn" > "$ASTLINUX_RELEASE"
}

REPO_ROOT="$(LANG=C svn info | awk -F': ' '/^Repository Root:/ { print $2 }')"

if [ -z "$REPO_ROOT" ]; then
  exit 1
fi

SVN="$(cat $ASTLINUX_RELEASE)"

if [ "svn" != "$SVN" ]; then
  echo "master-tag: Current directory is not in SVN branch"
  exit 1
fi

if ! svn up; then
  exit 1
fi

mark_release

svn ci -m "mark release '$RELEASE'"

if [ $? -ne 0 ]; then
  mark_svn
  exit 1
fi

svn copy ${REPO_ROOT}/branches/${BRANCH} ${REPO_ROOT}/tags/${1} -m "create ${1} tag"

mark_svn

svn ci -m "return to release 'svn'"

svn up

exit 0
