#!/bin/bash
#
# master-build output_path [ force ]
#

output_path="$1"

force="$2"

FAT_SIZE=256

BOARDS_SMP="geni586 geni586-serial"

BOARDS_NO_SMP="net5501 alix via via-serial viac7 viac7-serial net4801 wrap"

RUNFS_DIR="output/build/runfs"

build_board()
{
  local firmware="$1" img="$2"

  mkdir "$output_path/$firmware/$board"
  mkdir "$output_path/$img/$board"

  ./scripts/build $board

  if [ $? -ne 0 ]; then
    exit 1
  fi

  ASTVER="$(cat ${RUNFS_DIR}/os/ver)"

  if [ -z "$ASTVER" ]; then
    echo "master-build: missing runfs version file."
    exit 1
  fi

  ./scripts/astlinux-makeimage -z $FAT_SIZE $FAT_SIZE 0

  mv "${ASTVER}.tar.gz" "$output_path/$firmware/$board/${ASTVER}.tar.gz"
  mv "${ASTVER}.tar.gz.sha1" "$output_path/$firmware/$board/${ASTVER}.tar.gz.sha1"
  mv "${ASTVER}.img.gz" "$output_path/$img/$board/${ASTVER}-${ASTERISK_VERSION}.img.gz"

  rm -rf "${ASTVER}"
}

set_smp_kernel()
{
  sed -i 's:^BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE="[^"]*":BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE="project/astlinux/geni586/linux-smp.config":' .config
}

if [ -z "$output_path" ]; then
  echo "usage: master-build output_path [ force ]"
  exit 1
fi

if [ -d "$output_path" ]; then
  if [ "$force" = "force" ]; then
    rm -rf "$output_path"
    if ! mkdir "$output_path"; then
      exit 1
    fi
  else
    echo "master-build: directory \"$output_path\" exists, use 'force' verb to override."
    exit 1
  fi
else
  if ! mkdir "$output_path"; then
    exit 1
  fi
fi

echo "Regenerate the initrd"
rm -f initrd.img

#
# Build Asterisk 1.4 AstLinux
#

ASTERISK_VERSION="$(awk -F'=' '/^ASTERISK_VERSION/ { if ($2 ~ /^ *1.4/) {print $2; exit} }' package/asterisk/asterisk.mk)"
ASTERISK_VERSION="asterisk-${ASTERISK_VERSION// /}"

if ! mkdir "$output_path/firmware-1.x"; then
  exit 1
fi
if ! mkdir "$output_path/img"; then
  exit 1
fi

# Non-SMP Builds
echo "Cleaning out any existing builds..."
rm -rf output

cp astlinux.config .config

for board in $BOARDS_NO_SMP; do
  build_board "firmware-1.x" "img"
done

# SMP Builds
echo "Cleaning out any existing builds..."
rm -rf output

cp astlinux.config .config
set_smp_kernel

for board in $BOARDS_SMP; do
  build_board "firmware-1.x" "img"
done

#
# Build Asterisk 1.8 AstLinux
#

ASTERISK_VERSION="$(awk -F'=' '/^ASTERISK_VERSION/ { if ($2 ~ /^ *1.8/) {print $2; exit} }' package/asterisk/asterisk.mk)"
ASTERISK_VERSION="asterisk-${ASTERISK_VERSION// /}"

if ! mkdir "$output_path/ast18-firmware-1.x"; then
  exit 1
fi
if ! mkdir "$output_path/ast18-img"; then
  exit 1
fi

# Non-SMP Builds
echo "Cleaning out any existing builds..."
rm -rf output

cp astlinux18.config .config

for board in $BOARDS_NO_SMP; do
  build_board "ast18-firmware-1.x" "ast18-img"
done

# SMP Builds
echo "Cleaning out any existing builds..."
rm -rf output

cp astlinux18.config .config
set_smp_kernel

for board in $BOARDS_SMP; do
  build_board "ast18-firmware-1.x" "ast18-img"
done

echo "
##
## Master Build Successful for ${ASTVER}
##
"

