#!/bin/bash

TVER="1.5"

BRANCH="trunk"

if [ "${1:0:4}" != "${TVER}." ]; then
  echo "Usage: master-tag ${TVER}.x"
  exit 1
fi

RELEASE="astlinux-${1}"

ASTLINUX_RELEASE="project/astlinux/target_skeleton/etc/astlinux-release"

ASTLINUX_CHANGELOG="docs/ChangeLog.txt"

mark_release()
{
  echo "$RELEASE" > "$ASTLINUX_RELEASE"

  sed -i "s/^Released @TBD@/Released $(date +%Y-%m-%d)/" "$ASTLINUX_CHANGELOG"
}

mark_svn()
{
  local error="$1"

  echo "svn" > "$ASTLINUX_RELEASE"

  if [ "$error" = "error" ]; then
    sed -i "s/^Released $(date +%Y-%m-%d)/Released @TBD@/" "$ASTLINUX_CHANGELOG"
  else
    sed -i '8 i\
Additions for AstLinux '$TVER'.'$(($(echo "$RELEASE" | cut -d'.' -f3)+1))':\
=============================\
\
Released @TBD@\
\
' "$ASTLINUX_CHANGELOG"
  fi
}

if ! svn info >/dev/null 2>&1; then
  echo "Tagging astlinux requires a svn checkout, exiting."
  exit 1
fi

REPO_ROOT="$(LANG=C svn info | awk -F': ' '/^Repository Root:/ { print $2 }')"

if [ -z "$REPO_ROOT" ]; then
  exit 1
fi

SVN="$(cat $ASTLINUX_RELEASE)"

if [ "svn" != "$SVN" ]; then
  echo "master-tag: Current directory is not in SVN branch"
  exit 1
fi

if ! svn up; then
  exit 1
fi

mark_release

svn ci -m "mark release '$RELEASE'"

if [ $? -ne 0 ]; then
  mark_svn error
  exit 1
fi

svn copy ${REPO_ROOT}/${BRANCH} ${REPO_ROOT}/tags/${1} -m "create ${1} tag"

mark_svn

svn ci -m "return to release 'svn'"

svn up

exit 0
