#!/bin/bash
#
# Use BuildRoot "post-build" script to overlay board specific files
#

target="$1"

base="${target%/output/target}"

## Our target skeleton copying does not include dot-files
## Do it here:
ln -snf "/tmp/.ssh" "$target/.ssh"

. "$base/scripts/ver-label/runnix_release_version.sh"
runnix_release_version
echo ${RUNVER} > "$target/etc/runnix-release"

echo "
##
## RUNNIX Post Build Target Overlay: Release = \"$RUNVER\"
##
"

exit 0

