#!/bin/sh
# Print additional version information for non-release trees.

usage() {
  echo "Usage: $0 [srctree]" >&2
  exit 1
}

cd "${1:-.}" || usage

# Check for git and a git repo.
if head="$(git rev-parse --verify --short HEAD 2>/dev/null)"; then

  printf '%s%s' -g "$head"

  # All done with git
  exit
fi

# Check for svn and a svn repo.
if rev="$(LANG=C svn info 2>/dev/null | grep '^Last Changed Rev')"; then
  rev="$(echo $rev | awk '{print $NF}')"

  printf '%s%s' -svn "$rev"

  # All done with svn
  exit
fi
