#############################################################
#
# dosfstools
#
#############################################################
DOSFSTOOLS_VERSION = 3.0.25
DOSFSTOOLS_SOURCE = dosfstools-$(DOSFSTOOLS_VERSION).tar.gz
DOSFSTOOLS_SITE = http://daniel-baumann.ch/files/software/dosfstools
DOSFSTOOLS_LDFLAGS = $(TARGET_LDFLAGS)

ifneq ($(BR2_ENABLE_LOCALE),y)
DOSFSTOOLS_DEPENDENCIES += libiconv
DOSFSTOOLS_LDFLAGS += -liconv
endif

FATLABEL_BINARY = fatlabel
FSCK_FAT_BINARY = fsck.fat
MKFS_FAT_BINARY = mkfs.fat

FATLABEL_DOSFSLABEL_LINK = dosfslabel
FSCK_FAT_DOSFSCK_LINK = dosfsck
MKFS_FAT_MKDOSFS_LINK = mkdosfs

define DOSFSTOOLS_BUILD_CMDS
	$(MAKE) CFLAGS="$(TARGET_CFLAGS)" CC="$(TARGET_CC)" \
		LDFLAGS="$(DOSFSTOOLS_LDFLAGS)" -C $(@D)
endef

DOSFSTOOLS_INSTALL_BIN_FILES_$(BR2_PACKAGE_DOSFSTOOLS_DOSFSLABEL)+=$(FATLABEL_BINARY)
DOSFSTOOLS_INSTALL_BIN_FILES_$(BR2_PACKAGE_DOSFSTOOLS_DOSFSCK)+=$(FSCK_FAT_BINARY)
DOSFSTOOLS_INSTALL_BIN_FILES_$(BR2_PACKAGE_DOSFSTOOLS_MKDOSFS)+=$(MKFS_FAT_BINARY)

define DOSFSTOOLS_INSTALL_TARGET_CMDS
	test -z "$(DOSFSTOOLS_INSTALL_BIN_FILES_y)" || \
	install -m 755 $(addprefix $(@D)/,$(DOSFSTOOLS_INSTALL_BIN_FILES_y)) $(TARGET_DIR)/sbin/
	ln -sf $(FATLABEL_BINARY) $(TARGET_DIR)/sbin/$(FATLABEL_DOSFSLABEL_LINK)
	ln -sf $(FSCK_FAT_BINARY) $(TARGET_DIR)/sbin/$(FSCK_FAT_DOSFSCK_LINK)
	ln -sf $(MKFS_FAT_BINARY) $(TARGET_DIR)/sbin/$(MKFS_FAT_MKDOSFS_LINK)
endef

define DOSFSTOOLS_UNINSTALL_TARGET_CMDS
	rm -f $(TARGET_DIR)/sbin/$(FATLABEL_BINARY) $(TARGET_DIR)/sbin/$(FATLABEL_DOSFSLABEL_LINK)
	rm -f $(TARGET_DIR)/sbin/$(FSCK_FAT_BINARY) $(TARGET_DIR)/sbin/$(FSCK_FAT_DOSFSCK_LINK)
	rm -f $(TARGET_DIR)/sbin/$(MKFS_FAT_BINARY) $(TARGET_DIR)/sbin/$(MKFS_FAT_MKDOSFS_LINK)
endef

define DOSFSTOOLS_CLEAN_CMDS
	-$(MAKE) -C $(@D) clean
endef

$(eval $(call GENTARGETS,package,dosfstools))
