#!/bin/sh

LOCKFILE="/var/lock/fossil-update.lock"

if ! cd /mnt/kd; then
  exit 1
fi

if [ -f "$LOCKFILE" ]; then
  echo "fossil-update: already running, lockfile \"$LOCKFILE\" exists, process id: $(cat "$LOCKFILE")." >&2
  exit 9
fi

fossil close --force
