#!/bin/sh

export FOSSIL_HOME="/mnt/kd/fossil"

LOCKFILE="/var/lock/fossil-commit.lock"

if ! cd /mnt/kd; then
  exit 1
fi

if [ -f "$LOCKFILE" ]; then
  echo "fossil-commit: already running, lockfile \"$LOCKFILE\" exists, process id: $(cat "$LOCKFILE")." >&2
  exit 9
fi

fossil close --force
