#!/bin/sh

REPO="/mnt/kd/fossil/astlinux.fossil"

if [ ! -f $REPO ]; then
  echo "Fossil repository not found: $REPO" >&2
  exit 1
fi

if ! cd /mnt/kd; then
  exit 1
fi

fossil open $REPO --keep >/dev/null
fossil status
