#!/bin/sh

REPO="/mnt/kd/fossil/astlinux.fossil"

LOCKFILE="/var/lock/fossil-update.lock"

revision="$1"

file="$2"

if [ -z "$revision" -o -z "$file" ]; then
  echo "Usage: fossil-revert hex_revision_num file_name"
  exit 1
fi

if [ ! -f $REPO ]; then
  echo "Fossil repository not found: $REPO" >&2
  exit 1
fi

if ! cd /mnt/kd; then
  exit 1
fi

if [ ! -f "$file" ]; then
  echo "fossil-revert: file not found: /mnt/kd/${file#/mnt/kd/}" >&2
  exit 1
fi

if [ -f "$LOCKFILE" ]; then
  echo "fossil-update: already running, lockfile \"$LOCKFILE\" exists, process id: $(cat "$LOCKFILE")." >&2
  exit 9
fi

fossil open $REPO --keep >/dev/null

fossil revert -r "$revision" "$file"
rtn=$?

if [ $rtn -eq 0 ]; then
  fossil changes
  fossil commit --no-warnings -m "Revert file: $file"
  rtn=$?
fi

fossil close --force

exit $rtn
