#!/bin/sh

. /etc/rc.conf

export FOSSIL_HOME="/mnt/kd/fossil"

message="${1:-auto commit via cron}"

REPO="/mnt/kd/fossil/astlinux.fossil"

if [ ! -f $REPO ]; then
  echo "Fossil repository not found: $REPO" >&2
  exit 1
fi

if ! cd /mnt/kd; then
  exit 1
fi

fossil open $REPO --keep >/dev/null
fossil status

## Check for locally added files in selected directories, add them to the repo

if [ -n "$FOSSIL_DEFAULT_DIRS" ]; then
  dirs="$FOSSIL_DEFAULT_DIRS"
else
  dirs="rc.conf.d monit/monit.d"
  if [ "$ASTERISK_DAHDI_DISABLE" != "yes" ]; then
    dirs="$dirs asterisk dahdi fop2 phoneprov/templates"
  fi
fi

unset IFS
for dir in $dirs $FOSSIL_INCLUDE_DIRS; do
  if [ -d $dir ]; then
    fossil add --force $dir
  fi
done

## Check for locally deleted files, remove them from the repo
if fossil changes | grep -q '^MISSING'; then
  fossil changes | awk '/^MISSING/ { print $2; }' | xargs fossil forget
fi

fossil commit --no-warnings -m "$message"
rtn=$?

fossil close --force

exit $rtn
