#!/bin/sh

## kexec based quick reboot for AstLinux
## Replicate the basic functionality of the RUNNIX script
##
## If anything fails, do a normal reboot

ARGS="$1$2"

usage()
{
  echo '
Usage: kernel-reboot [-d DELAY]

Reboot the system using kexec as RUNNIX does

Options:
    -d SEC    Delay interval
'
  exit 1
}

do_failure()
{
  echo '## Falling back to /sbin/reboot ##'
  sleep 1
  /sbin/reboot
  exit 1
}

do_reboot()
{
  echo ''
  echo '## Using /sbin/kernel-reboot ##'

  BASE="/oldroot/cdrom"

  if ! mount | grep -q "$BASE"; then
    LABEL="$(/sbin/findfs LABEL=RUNNIX)"
    if [ -n "$LABEL" ]; then
      mount -t vfat -o ro "$LABEL" $BASE
    fi
    if ! mount | grep -q "$BASE"; then
      echo "Unable to find RUNNIX partition."
      do_failure
    fi
  fi

  ROOT="/tmp/mnt/root"

  mkdir -p "$ROOT"

  if [ -f $BASE/os/default.conf ]; then
    . $BASE/os/default.conf
  fi

  # Get the latest good one
  cd $BASE/os
  RUNIMG="$(ls *.run | tail -n1)"

  # If we have a ver file, override auto/default.conf value
  if [ -f $BASE/os/ver ]; then
    RUNIMG="$(cat $BASE/os/ver).run"
  fi

  if [ "$VERIFY_LOCAL" = "yes" ]; then
    echo "Verifying $RUNIMG..."

    if sha1sum -cs $RUNIMG.sha1; then
      echo "$RUNIMG verified"
      IMGVER=1
    else
      echo "$RUNIMG not verified"
    fi
  else
    echo "Skip Verifying $RUNIMG"
  fi

  if [ -f $BASE/os/$RUNIMG.conf ]; then
    . $BASE/os/$RUNIMG.conf
  fi

  # Fixup RUNNIX -> Astlinux paths
  INITRD="${BASE}${INITRD#/mnt/base}"
  KERN="${ROOT}${KERN#/mnt/root}"

  # Find first unused loop device
  DEVLOOP="$(losetup -f)"

  if [ -z "$OFFSET" ]; then
    losetup $DEVLOOP $BASE/os/$RUNIMG
  else
    losetup -o "$OFFSET" $DEVLOOP $BASE/os/$RUNIMG
  fi

  if [ -z "$FSTYPE" ]; then
    FSTYPE="ext4"
  fi

  if ! mount -t $FSTYPE -o ro $DEVLOOP $ROOT; then
    echo "Error mounting $RUNIMG root fs"
    do_failure
  fi

  if [ -n "$INITRD" ]; then
    if [ -f "$INITRD" ]; then
      echo "Custom initrd $INITRD found"
    else
      INITRD="$BASE/os/initrd.img"
      echo "Custom initrd not found - using $INITRD"
    fi
  else
    echo "Using default initrd"
    INITRD="$BASE/os/initrd.img"
  fi

  if [ -n "$KERN" ]; then
    if [ -f "$KERN" ]; then
      echo "Custom kernel $KERN found"
    else
      KERN="$ROOT/boot/bzImage"
      echo "Custom kernel not found - using $KERN"
    fi
  else
    echo "Using default kernel"
    KERN="$ROOT/boot/bzImage"
  fi

  if [ -n "$KCMD" -a -f "$INITRD" -a -f "$KERN" ]; then
    echo "Loading new kernel..."
    if ! /sbin/kexec -l --command-line="$KCMD" --initrd="$INITRD" "$KERN"; then
      umount $ROOT
      do_failure
    fi
    umount $ROOT
  else
    echo "Missing one or more of: kcmd, initrd, kernel"
    umount $ROOT
    do_failure
  fi

  cd /root
  losetup -d $DEVLOOP

  # Stop services and unmount all file systems or remount 'ro' if busy
  /etc/rc shutdown

  echo "Trying kexec..."
  /sbin/kexec -e

  echo '## Falling back to /sbin/reboot ##'
  sleep 1
  /sbin/reboot -f
  exit 1
}

# Set a working dir for when called via PHP
cd /root

if [ ! -x /sbin/kexec ]; then
  echo "kernel-reboot: You don't have kexec-tools installed, falling back to /sbin/reboot" >&2
  /sbin/reboot
  exit 1
fi

if [ ! -x /sbin/findfs ]; then
  echo "kernel-reboot: You don't have findfs installed, falling back to /sbin/reboot" >&2
  /sbin/reboot
  exit 1
fi

DELAY=0

if [ -n "$ARGS" ]; then
  case "$ARGS" in
    -d*) DELAY="${ARGS#-d}"
         DELAY="$(echo "$DELAY" | tr -c -d '0-9')" ;;
      *) usage ;;
  esac
fi

if [ $(id -u) -ne 0 ]; then
  echo "kernel-reboot: Operation not permitted, must be root" >&2
  exit 1
fi

if [ -n "$DELAY" ] && [ $DELAY -gt 0 ]; then
  sleep $DELAY
fi

sync

# Ignore terminating signals from here on
trap '' HUP INT TERM

do_reboot >/dev/console 2>&1 &
