#!/bin/sh

##
## asterisk-sip-monitor-ctrl to manage the asterisk-sip-monitor
## background process
##

start()
{
  if [ ! -f /var/lock/asterisk-sip-monitor.lock ]; then
    echo "Starting asterisk-sip-monitor..."

    # Start the background process
    start-stop-daemon -S -x /usr/sbin/asterisk-sip-monitor -b
  fi
}

stop()
{
  if [ -f /var/run/asterisk-sip-monitor.pid ]; then
    echo "Stopping asterisk-sip-monitor..."

    #
    # kill $(cat /var/run/asterisk-sip-monitor.pid)
    # is not necessary.  Removing the PID file is sufficient
    # because the background process monitors its PID file.
    #
    rm -f /var/run/asterisk-sip-monitor.pid
    
    # Wait for the background process to exit
    cnt=10
    while [ $cnt -gt 0 -a -f /var/lock/asterisk-sip-monitor.lock ]; do
      cnt=$((cnt - 1))
      sleep 1
    done
  fi
}

status()
{
  echo ""
  
  if [ -f /var/lock/asterisk-sip-monitor.lock ]; then
    echo "Status: asterisk-sip-monitor is active"
  else
    echo "Status: asterisk-sip-monitor is stopped"
  fi

  if [ -f /var/tmp/asterisk_sip_monitor_alert ]; then
    echo "- Alerts have been generated for: $(cat /var/tmp/asterisk_sip_monitor_alert)"
  else
    echo "- No active Alerts"
  fi
  
  echo ""
}

case $1 in
  start)
    start
    ;;

  stop)
    stop
    ;;
  
  restart)
    stop
    start
    ;;

  status)
    status
    ;;

  *)
    echo "Usage: asterisk-sip-monitor-ctrl start|stop|restart|status"
    ;;
esac

